### ISSUE TITLE
delete_range/delete_prefix

### ISSUE THREAD

**Issue by marvin-j97** [fjall-rs/fjall#33]
- [ ] Implement in https://github.com/fjall-rs/lsm-tree/issues/2
- [ ] Implement in journal
- [ ] Implement in partition
- [ ] Implement in transaction

**Comment by marvin-j97** [comment]
We can probably support this already for transactions using scan + delete

**Comment by crepererum** [comment]
There are currently two issues with the "scan + delete" approach:

1. you have to load the values as well, at least until https://github.com/fjall-rs/lsm-tree/issues/110 is fixed+exposed
2. you have to collect all keys (e.g. into a vector) before you can delete them, because the iterator captures the mutable reference to the transaction, so you cannot use it to delete entries in the `for`-loop body

**Comment by marvin-j97** [comment]
> you have to collect all keys (e.g. into a vector) before you can delete them, because the iterator captures the mutable reference to the transaction, so you cannot use it to delete entries in the for-loop body

Yeah that sucks a bit right now - this is because of the write set being a hash map of Memtables, but not using some concurrent hash map right now. May be easy to solve though.

**Comment by marvin-j97** [comment]
Actually wait, the scanning function just doesn't need to use the `delete` function, but rather some internal delete function, or the memtable function directly - the memtable does not need &mut.
Then it does not have to index into the hash map all the time either, instead:
```rs
// Get or create memtable
let memtable = self.memtables.entry(partition.name)...

for kv in self.iter() {
  // as you mentioned, use kv.key() once that API is available
  memtable.insert(Tombstone(kv.key));
}
```
